# SPDX-FileCopyrightText: 2019-2022 Heiko Schaefer <heiko@schaefer.name>
# SPDX-License-Identifier: CC0-1.0

stages:
  - lint
  - test
  - doc
  - deploy

image: rust:latest

reuse:
  stage: lint
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint

cargo-fmt:
  stage: lint
  script:
    - rustup toolchain install nightly && rustup component add --toolchain nightly rustfmt
    - cargo +nightly fmt -- --check

cargo-clippy:
  stage: lint
  before_script:
    - mkdir -p /run/user/$UID
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends  git rustc cargo clang make pkg-config nettle-dev libssl-dev capnproto libsqlite3-dev ca-certificates valgrind strace python3-dev python3-setuptools python3-cffi python3-pytest gnupg libpcsclite-dev
    - apt clean
  script:
    - rustup component add clippy
    - cargo clippy --verbose --tests -- -D warnings

cargo-test:
  stage: test
  before_script:
    - mkdir -p /run/user/$UID
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends  git rustc cargo clang make pkg-config nettle-dev libssl-dev capnproto libsqlite3-dev ca-certificates valgrind strace python3-dev python3-setuptools python3-cffi python3-pytest gnupg libpcsclite-dev
    - apt clean
  script:
    - cargo test

cargo-test-card:
  image: registry.gitlab.com/openpgp-card/virtual-cards/opcard-rs-builddeps
  stage: test
  before_script:
    - mkdir -p /run/user/$UID
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends  git rustc cargo clang make pkg-config nettle-dev libssl-dev capnproto libsqlite3-dev ca-certificates valgrind strace python3-dev python3-setuptools python3-cffi python3-pytest gnupg libpcsclite-dev
    - apt clean
    - sh /start.sh
  script:
    # No parallelism ("--jobs 1")!
    # There is only one virtual card in the CI environment,
    # it can't be used from multiple tests in parallel.
    - IDENT="0000:00000000" cargo test --jobs 1 --package openpgp-ca-lib --no-default-features --features card

pages:
  stage: doc
  image: alpine:latest
  script:
    - echo 'pages'
  artifacts:
    paths:
      - public
  only:
    - main

build_docker:
  stage: deploy
  image: docker:stable

  variables:
    IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest
    IMAGE_SHA: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  services:
      - docker:stable-dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $IMAGE_LATEST || true
    - docker build --cache-from $IMAGE_LATEST --target openpgp-ca -t $IMAGE_SHA -t $IMAGE_LATEST .
    - docker push $IMAGE_SHA
    - docker push $IMAGE_LATEST
  needs: []

build_docker_restd:
  stage: deploy
  image: docker:stable

  variables:
    IMAGE_LATEST: $CI_REGISTRY_IMAGE/openpgp-ca-restd:latest
    IMAGE_SHA: $CI_REGISTRY_IMAGE/openpgp-ca-restd:$CI_COMMIT_SHA
  services:
    - docker:stable-dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $IMAGE_LATEST || true
    - docker build --cache-from $IMAGE_LATEST --target openpgp-ca-restd -t $IMAGE_SHA -t $IMAGE_LATEST .
    - docker push $IMAGE_SHA
    - docker push $IMAGE_LATEST
  needs: []
